# necessary for conformance
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "IPv6DualStack=true"
  scheduler:
    extraArgs:
      "feature-gates": "IPv6DualStack=true"
  controllerManager:
    extraArgs:
      "feature-gates": "IPv6DualStack=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "IPv6DualStack=true"
networking:
  ipFamily: dual
nodes:
# the control plane node
- role: control-plane
- role: worker
- role: worker

